# COMPILE SOURCE CODE MAIN FILES
gcc -ffreestanding -m32 -g -c "WebArchy/src/browser.c" -o "WebArchy/bin/browser.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/others.c" -o "WebArchy/bin/others.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/render.c" -o "WebArchy/bin/render.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/view.c" -o "WebArchy/bin/view.o"

# COMPILE SOURCE CODE USING QUICK JS FILES
gcc -ffreestanding -m32 -g -c "WebArchy/src/qjs_runtime.c" -o "WebArchy/bin/qjs_runtime.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/qjs_stuff.c" -o "WebArchy/bin/qjs_stuff.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/qjs_port.c" -o "WebArchy/bin/qjs_port.o"

# COMPILE QUICK JS CODE FILES
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/cutils.c" -o "WebArchy/bin/quickjs/cutils.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/dtoa.c" -o "WebArchy/bin/quickjs/dtoa.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/libregexp.c" -o "WebArchy/bin/quickjs/libregexp.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/libunicode.c" -o "WebArchy/bin/quickjs/libunicode.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/quickjs-libc.c" -o "WebArchy/bin/quickjs/quickjs-libc.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/unicode_gen.c" -o "WebArchy/bin/quickjs/unicode_gen.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/qjsc.c" -o "WebArchy/bin/quickjs/qjsc.o"
gcc -ffreestanding -m32 -g -c "WebArchy/src/quickjs/quickjs.c" -o "WebArchy/bin/quickjs/quickjs.o"
